config/routes.rb
ActiveServer::Application.routes.draw do

  resources :posters do
     resources :contentlists
  end

  resource :user_session

  resources :users 
  
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
  root :to => 'posters#index'
  get 'getcontent' => 'dummy#getcontent'

end

app/models/poster.rb
class Poster < ActiveRecord::Base
  has_many :contentlists, dependent: :destroy
end

app/controllers/posters_controller.rb
class PostersController < ApplicationController
  # GET /posters
  # GET /posters.xml
  def index
    @posters = Poster.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @posters }
    end
  end

  # GET /posters/1
  # GET /posters/1.xml
  def show
    @poster = Poster.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json  { render :json => @poster }
    end
  end

  # GET /posters/new
  # GET /posters/new.xml
  def new
    @poster = Poster.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @poster }
    end
  end

  # GET /posters/1/edit
  def edit
    @poster = Poster.find(params[:id])
  end

  # POST /posters
  # POST /posters.xml
  def create
    @poster = Poster.new(params[:poster])

    respond_to do |format|
      if @poster.save
        format.html { redirect_to(@poster, :notice => 'Poster was successfully created.') }
        format.xml  { render :xml => @poster, :status => :created, :location => @poster }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @poster.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /posters/1
  # PUT /posters/1.xml
  def update
    @poster = Poster.find(params[:id])

    respond_to do |format|
      if @poster.update_attributes(params[:poster])
        format.html { redirect_to(@poster, :notice => 'Poster was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @poster.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /posters/1
  # DELETE /posters/1.xml
  def destroy
    @poster = Poster.find(params[:id])
    @poster.destroy

    respond_to do |format|
      format.html { redirect_to(posters_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/posters_helper.rb
module PostersHelper
end

app/views/posters/_form.html.haml
= form_for @poster do |f|
  -if @poster.errors.any?
    #error_explanation
      %h2= "#{pluralize(@poster.errors.count, "error")} prohibited this poster from being saved:"
      %ul
        - @poster.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :Postername
    = f.text_field :postername
  .field
    = f.label :location
    = f.text_area :location
  .field
    = f.label :direction
    = f.text_area :direction
  .field
    = f.label :phoneport
    = f.number_field :phoneport
  .field
    = f.label :beacon
    = f.text_area :beacon
  .field
    = f.label :serverip
    = f.text_field :serverip
  .field
    = f.label :serverport
    = f.number_field :serverport
  .field
    = f.label :Postertype
    = f.text_field :postertype
  .actions
    = f.submit 'Save'

app/views/posters/edit.html.haml
%h1 Editing poster

= render 'form'

= link_to 'Show', @poster
\|
= link_to 'Back', posters_path

app/views/posters/index.html.haml
%h1 Listing posters

%table
  %tr
    %th Name
    %th 
    %th
    %th
    %th

  - @posters.each do |poster|
    %tr
      %td= link_to poster.postername , poster
      !!!%td= poster.beacon
      %td= link_to 'Show Linked Content', poster_contentlists_path(poster)
      !!!%td= link_to 'Edit', edit_poster_path(poster)
      %td= link_to 'Destroy', poster, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Poster', new_poster_path

app/views/posters/new.html.haml
%h1 New poster

= render 'form'

= link_to 'Back', posters_path

app/views/posters/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @poster.postername
%p
  %b Direction:
  = @poster.direction
%p
  %b Beacon:
  = @poster.beacon
%p
  %b Server Ip:
  = @poster.serverip
%p
  %b Server Port:
  = @poster.serverport
%p
  %b Phone port:
  = @poster.phoneport
%p
  %b Location:
  = @poster.location
%p
  %b PosterType:
  = @poster.postertype

= link_to 'Edit', edit_poster_path(@poster)
\|
= link_to 'Back', posters_path