config/routes.rb
ActiveServer::Application.routes.draw do

  resources :posters do
     resources :contentlists
  end

  resource :user_session

  resources :users 
  
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
  root :to => 'posters#index'
  get 'getcontent' => 'dummy#getcontent'

end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_authentic
  has_many :terminals, :dependent => :destroy
  has_many :authentications, :dependent => :destroy
  has_many :videos, :dependent => :destroy
  has_many :subscriptions, :dependent => :destroy
  has_many :providers, :through => :subscriptions

  def graph
    provider = self.authentications.find_by_provider("facebook")
    @graph ||= provider ? Koala::Facebook::API.new(provider["credential"]) : nil
    return @graph
  end

  def facebook?
    return !self.authentications.find_by_provider("facebook").nil?
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
    respond_to do |format|
        format.html 
        format.json {render :json => {:users => @users}}
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(params[:user])

    if @user.save
      redirect_to(@user, :notice => 'User was successfully created.')
    else
      render :action => "new"
    end
  end

  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(@user, :notice => 'User was successfully updated.') }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to(users_url) }
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.haml
= semantic_form_for(@user) do |f|
  - if @user.errors.any?
    #error_explanation
      %h2
        = pluralize(@user.errors.count, "error")
        prohibited this user from being saved:
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg
  = f.inputs :name => "User" do
    = f.input :username
    = f.input :password
    = f.input :password_confirmation
    = f.input :email
    = f.input :quota
    = f.input :cycled
    = f.input :providers, :as => :check_boxes, :label => "Provider", :hint => "Select content providers for the user", :include_blank => false, :collection => Provider.all

  %br
  %br
  %br
  = f.buttons

app/views/users/edit.html.haml
=content_for :section do
  Edit user

= render 'form'

=content_for :menu do
  %li= link_to 'Current user', user_path(@user)
  %li= link_to 'Videos', user_videos_path(@user)
  %li= link_to 'Terminals', user_terminals_path(@user)

app/views/users/index.html.erb
<%= content_for :section do %>
Listing users
<% end %>

<table>
  <tr>
    <th>Username</th>
    <th>Email</th>
    <th>Auths</th>
    <th>Subscriptions</th>
    <th>Terminals</th>
    <th>Videos</th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <% if (current_user == user) %>
    <tr class="me">
  <% else %>
    <tr>
  <% end %>
    <td><%= link_to user.username, user_path(user) %></td>
    <td><%= user.email %></td>
    <td><%= link_to user.authentications.count, user_authentications_path(user) %> </td>
    <td><%= link_to user.providers.count, user_subscriptions_path(user) %> </td>
    <td><%= link_to user.terminals.count, user_terminals_path(user) %> </td>
    <td><%= link_to user.videos.count, user_videos_path(user) %> </td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<%=content_for :menu do%>
  <li><%= link_to 'New User', new_user_path %></li>
<% end %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<%= content_for :section do %>
  Show user
<% end %>
<p>
  <b>Username:</b>
  <%= @user.username %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Providers:</b>
  <% if @user.providers.empty? %>
    None (edit user to add)
  <% else %>
    <ul>
      <% @user.providers.each do |provider| %>
        <li class="content_provider"><%= provider.name %> </li>
      <% end %>
    </ul>
  <% end %>
</p>

<%=content_for :menu do %>
  <li><%= link_to 'Terminals', user_terminals_path(@user) %></li>
  <li><%= link_to 'Videos', user_videos_path(@user) %></li>
  <li><%= link_to 'Authentications', user_authentications_path(@user) %></li>
  <li><%= link_to 'Subscriptions', user_subscriptions_path(@user) %></li>
  <li><%= link_to 'Edit', edit_user_path(@user) %></li>
<% end %>