config/routes.rb
ActiveServer::Application.routes.draw do

  resources :posters do
     resources :contentlists
  end

  resource :user_session

  resources :users 
  
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
  root :to => 'posters#index'
  get 'getcontent' => 'dummy#getcontent'

end

app/models/contentlist.rb
class Contentlist < ActiveRecord::Base
  belongs_to :poster
end

app/controllers/contentlists_controller.rb
class ContentlistsController < ApplicationController
  before_filter :get_poster
  # GET /contentlists
  # GET /contentlists.xml
  def index
    @contentlists = @poster.contentlists

    respond_to do |format|
      format.html # index.html.erb
      #format.xml  { render :xml => @contentlists }
    end
  end

  # GET /contentlists/1
  # GET /contentlists/1.xml
  #def show
  #  @contentlist = @poster.contentlists.find(params[:id])

  #  respond_to do |format|
  #    format.html # show.html.erb
  #    format.xml  { render :xml => @contentlist }
  #  end
  #end

  # GET /contentlists/new
  # GET /contentlists/new.xml
  def new
    #@contentlist = Contentlist.new
    @contentlist = @poster.contentlists.new

    respond_to do |format|
      format.html # new.html.erb
      #format.xml  { render :xml => @contentlist }
    end
  end

  # GET /contentlists/1/edit
  def edit
    @contentlist = @poster.contentlists.find(params[:id])
  end

  # POST /contentlists
  # POST /contentlists.xml
  def create
    @contentlist = @poster.contentlists.new(params[:contentlist])

    respond_to do |format|
      if @contentlist.save
        format.html { redirect_to(poster_contentlists_path, :notice => 'Contentlist was successfully created.') }
        #format.xml  { render :xml => @contentlist, :status => :created, :location => @contentlist }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @contentlist.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /contentlists/1
  # PUT /contentlists/1.xml
  def update
    @contentlist = @poster.contentlists.find(params[:id])

    respond_to do |format|
      if @contentlist.update_attributes(params[:contentlist])
        format.html { redirect_to(poster_contentlists_path, :notice => 'Contentlist was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @contentlist.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /contentlists/1
  # DELETE /contentlists/1.xml
  def destroy
    @contentlist = @poster.contentlists.find(params[:id])
    @contentlist.destroy

    respond_to do |format|
      format.html { redirect_to(poster_contentlists_path) }
      format.xml  { head :ok }
    end
  end
  def get_poster
    @poster = Poster.find(params[:poster_id])
  end
end

app/helpers/contentlists_helper.rb
module ContentlistsHelper
end

app/views/contentlists/_form.html.haml
= form_for [@poster, @contentlist] do |f|
  -if @contentlist.errors.any?
    #error_explanation
      %h2= "#{pluralize(@contentlist.errors.count, "error")} prohibited this contentlist from being saved:"
      %ul
        - @contentlist.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :interactiontype
    = f.text_field :interactiontype
  .field
    = f.label :contentid
    = f.text_field :contentid
  .actions
    = f.submit 'Save'

app/views/contentlists/edit.html.haml
%h1 Editing contentlist

= render 'form'

!!!= link_to 'Show', poster_contentlist(@poster,contentlist)
!!!= link_to 'Back', poster_contentlists_path

app/views/contentlists/index.html.haml
%h1 Listing contentlists

%table
  %tr
    %th Name
    %th Interactiontype
    %th Contentid
    %th Poster
    %th
    %th
    %th

  - @contentlists.each do |contentlist|
    %tr
      %td= contentlist.name
      %td= contentlist.interactiontype
      %td= contentlist.contentid
      %td= @poster.postername
      !!!%td= link_to 'Show', poster_contentlist_path
      %td= link_to 'Edit', edit_poster_contentlist_path(@poster,contentlist)
      %td= link_to 'Destroy', poster_contentlist_path(@poster,contentlist), :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Contentlist', new_poster_contentlist_path

app/views/contentlists/new.html.haml
%h1 New contentlist

= render 'form', :poster => @poster

= link_to 'Back', poster_contentlists_path

app/views/contentlists/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @contentlist.name
%p
  %b Interactiontype:
  = @contentlist.interactiontype
%p
  %b Contentid:
  = @contentlist.contentid
%p
  %b Poster:
  = @contentlist.poster

= link_to 'Edit', edit_contentlist_path(@contentlist)
\|
= link_to 'Back', contentlists_path