config/routes.rb
ActiveServer::Application.routes.draw do

  resources :posters do
     resources :contentlists
  end

  resource :user_session

  resources :users 
  
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
  root :to => 'posters#index'
  get 'getcontent' => 'dummy#getcontent'

end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  def to_key
    new_record? ? nil : [self.send(self.class.primary_key) ]
  end

  def persisted?
    false
  end

  #oauth2_client_id      "256004954427982"
  #oauth2_client_secret  "f6b2908daf03a679e76fe6b460df6a85"
  #oauth2_site           "https://graph.facebook.com"
  #oauth2_scope          "offline_access,email,read_stream"
  #oauth2_cannot_find_record_message "We have no record of you in our database, please sign up first."

  #def self.oauth_consumer
  #  OAuth::Consumer.new("256004954427982", "f6b2908daf03a679e76fe6b460df6a85",
  #                      { :site => "http://facebook.com",
  #                        :authorize_url => "https://www.facebook.com/dialog/oauth"      
  #  })
  #end

end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  # GET /user_session/new
  def new
    @user_session = UserSession.new
  end

  # POST /user_session
  def create
    @user_session = UserSession.new(params[:user_session]) 

    @user_session.save do |result|
      if result
        respond_to do |format|
          format.html {redirect_to(:users, :notice => 'Login successful!')}
          format.json {render :json => {:success => true, :id => current_user.id} }
        end
      else
        respond_to do |format|
          format.html {render :action => "new"}
          format.json {render :json => {:success => false, :message => "Something went wrong. It couldn't login"}}
        end
      end
    end

  end

  # DELETE /user_session/1
  def destroy
    @user_session = UserSession.find
    if @user_session
      @user_session.destroy
      respond_to do |format|
        format.html {redirect_to(:users, :notice => "Goodbye!")}
        format.json {render :json => {:success => true, :message => "User logged out"}}
      end
    else
      respond_to do |format|
        format.html {redirect_to(:users, :notice => "The user was not logged in!")}
        format.json {render :json => {:success => false, :message => "The user was not logged in"}}
      end
    end
    
  end

end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/user_sessions/_form.html.erb
<%= form_for(@user_session, :url => user_session_path) do |f| %>
  <% if @user_session.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_session.errors.count, "error") %> prohibited this user_session from being saved:</h2>

      <ul>
      <% @user_session.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
      <%#= oauth2_login_button :value => "Facebook Login" %>
  <div class="actions">
    <%= f.submit "Login" %>
  </div>
<% end %>

app/views/user_sessions/edit.html.erb
<h1>Editing user_session</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_session %> |
<%= link_to 'Back', user_sessions_path %>

app/views/user_sessions/new.html.erb
<h1>Login</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>